### ISSUE TITLE
Fit file parsing error when no activities found

### ISSUE THREAD

**Issue by thomaschampagne** [sports-alliance/sports-lib#45]
Library throws 
`TypeError: Cannot read property 'timestamp' of undefined` 
AT `importer.fit.ts:171`

File to reproduce the bug: [7b2c46-522856231.zip](https://github.com/sports-alliance/sports-lib/files/4204225/7b2c46-522856231.zip)

**Comment by jimmykane** [comment]
Looks like an empty file :-/ 

<img width="314" alt="Screenshot 2020-02-14 at 13 40 18" src="https://user-images.githubusercontent.com/1268723/74527927-a8118880-4f2f-11ea-84ad-37d413a44e5e.png">


Should we detect this and throw a relevant error?

**Comment by thomaschampagne** [comment]
Indeed :)

If there is not activities. Why trying to create some in the block section `importer.fit.ts:168-186`?

Maybe return an empty EventInterface structure? Or a null EventInterface? 

When upload the fit file to strava. Strava UI returns: "The upload appears to be malformed and we are unable to process it."

**Comment by jimmykane** [comment]
It depends I think how you want to handle it. It's empty, but I think you
don't want to store something empty but rather handle this as a failure.

What do you think?

For me both ways work 🙄

**Comment by thomaschampagne** [comment]
On my side i will skip it and save nothing in db. In this case we are even unable to set the start date properly (right?).

On my side 
- it can be null = ok nothing to extract the file
- it can throw an error ideally with an "error code" to identify this case and skip the file.

The more simple could be a null EventInterface no? Except if the library has an error handler based on error codes.

Just to give you more context about this bug. I asked my community to send me a large number of files (https://twitter.com/champagnethomas/status/1227684968790462465)

I already have thousands of theses files on which I make the library suffer :)

**Comment by jimmykane** [comment]
Roger that. 

Would you prefer something like: `new Error(`Empty event`)`

Or `new EventImportError('No data')`

Something else? 

I tend to avoid returning `null` because typically with TS, you would want to avoid multiple type returns eg: `Event|null` , makes the later code more conditional based.  

Arguably if it was querying a DB `null` should be fine but now it's an operation (the import) that has to succeed or fail right? Not return "empty/null" 

I think this way you could handle this error and also inform the user with a relevant message/log

**Comment by thomaschampagne** [comment]
I understand your pov with `null`. A specialized error will be perfect ;) 

`SportsLibError <-- EventError <-- EmptyEventError `

I usually specialize errors by inheritance but i will fit to yours ;) 

I can perform the development ! Just tell me to do it through a PR ;)

Since typescript do not support properly Error inheritance (https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work)

We can use something like:

```typescript
class FooError extends Error {
    constructor(m: string) {
        super(m);

        // Set the prototype explicitly.
        Object.setPrototypeOf(this, FooError.prototype);
    }

    sayHello() {
        return "hello " + this.message;
    }
}
```
:)
